name             'drupal'
maintainer       'VAMPD'
maintainer_email 'tim.d.whitney@gmail.com'
license          'Apache 2.0'
description      'Manages Drupal'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '5.0.0'

depends 'apt', '~> 2.7.0'
depends 'apache2', '~> 3.0.1'
depends 'php', '~> 1.5.0'
depends 'mysql', '~> 6.0'
depends 'database', '~> 4.0.5'
depends 'ssh_known_hosts', '~> 2.0.0'
depends 'git', '~> 4.2.1'
depends 'composer', '~> 2.0.0'
depends 'mysql2_chef_gem', '~> 1.0'
